app.env: local

BASE_DIRECTORY: src/main/resources/
INPUT_XML: output/data_output.xml
OUTPUT_DOCX: output/Berchtoldschiessen_test.docx
INPUT_COMPETITORS: input/competitors.csv


INPUT_DOCX: Berchtoldschiessen_test2.docx